### ISSUE TITLE
It would be nice to have 0.0.4 on rubygems.org

### ISSUE THREAD

**Issue by edslocomb** [prawnpdf/prawn-templates#10]

**Comment by bvogel** [comment]
I currently have no rights to do this myself or I don't know the procedure yet. I already pinged @packetmonkey about this and I hope this will be fixed soon.

**Comment by packetmonkey** [comment]
@bvogel What is your username on `rubygems.org` ?

**Comment by bvogel** [comment]
@packetmonkey it's 'bvogel'

**Comment by packetmonkey** [comment]
Looks like I need to add you via email, what is the email you signed up with? You can email it to me if you don't want that to be public evan@packetmokey.org

**Comment by bvogel** [comment]
see @ https://github.com/prawnpdf/prawn-templates/blob/master/prawn-templates.gemspec

**Comment by packetmonkey** [comment]
:rotating_light: :rotating_light: :rotating_light: ACCESS GRANTED :rotating_light: :rotating_light: :rotating_light:

Go ahead and push releases as you see fit :+1:

Feel free to announce them on the prawn mailing list as well.

**Comment by bvogel** [comment]
I'm on vacation right now... Will do if I find the time.
