### ISSUE TITLE
Releases still not being published on rubygems

### ISSUE THREAD

**Issue by edslocomb** [prawnpdf/prawn-templates#11]
it looks like permission to push to rubygems [has been granted](https://github.com/prawnpdf/prawn-templates/issues/10#issuecomment-192326157), but the published version is still at 0.3

It would be nice to have 0.5 on rubygems!

**Comment by bvogel** [comment]
Hi, 0.0.5 is the current dev version (as to prawn versioning policy), but I finally found the time to push v0.0.4 to rubygems
