### ISSUE TITLE
Prawn content is vertically mirrored for PDFs exported by Google Chrome

### ISSUE THREAD

**Issue by ndbroadbent** [prawnpdf/prawn-templates#19]
I've collected the following links that demonstrate the problem:

* https://github.com/prawnpdf/prawn/issues/568
* https://github.com/prawnpdf/prawn/issues/393
* https://stackoverflow.com/questions/12076299/my-text-is-written-in-a-bad-direction-when-i-use-a-template

There's also a [very comprehensive StackOverflow answer](https://stackoverflow.com/a/12089301/304706) that might explain what's going on.

See also:

* https://github.com/wkhtmltopdf/wkhtmltopdf/issues/1599

This is a critical issue for my app, so I will attempt to fix it myself. I'll submit a PR if I manage to solve the problem. Any assistance would be greatly appreciated!

**Comment by ndbroadbent** [comment]
I've added a failing spec to my fork - https://github.com/FormAPI/prawn-templates/commit/60e3547d0145120f276ffd601ff0d32d6cd9d638

Script to reproduce:

```ruby
#!/usr/bin/env ruby
require 'bundler'
Bundler.setup

require 'prawn'
require './lib/prawn/templates'

filename = "#{DATADIR}/pdfs/google_chrome_print.pdf"
pdf = Prawn::Document.new(template: filename)

pdf.text 'Adding some text'

filename = '/tmp/prawn-template-test.pdf'
File.open(filename, 'wb') { |f| f.puts pdf.render }

# Open the PDF on Mac or Linux.
`type xdg-open > /dev/null 2&>1 && xdg-open '#{filename}' || open '#{filename}'`
```

Result:

<img width="293" alt="screen shot 2017-10-03 at 1 55 58 pm" src="https://user-images.githubusercontent.com/139536/31113274-aaaf6df0-a842-11e7-981f-0a09e3e6136e.png">

**Comment by ndbroadbent** [comment]
I've solved the issue, but it's a pretty crazy workaround, and I have no idea how to bring this into prawn-templates. Basically we have to parse the page stream and check if it starts with a `cm` operator (concatenate matrix). If so, then I apply that transformation matrix to the whole pdf.

I think this might just have to stay as an ugly workaround for now, but here's the code in case anyone else comes across this issue:

```ruby
# PDFs printed by Google Chrome or exported from Google Docs use a transformation matrix
# that flips everything vertically. We need to copy that matrix before adding content.
# Parsing code taken from:
# https://github.com/yob/pdf-reader/blob/master/lib/pdf/reader/page.rb#L139
def set_transformation_matrix(pdf, filename)
  pdf_reader = PDF::Reader.new(filename)
  return if pdf_reader.pages.empty?
  page = pdf_reader.pages.first

  buffer = PDF::Reader::Buffer.new(StringIO.new(page.raw_content), content_stream: true)
  parser = PDF::Reader::Parser.new(buffer)
  params = []

  while (token = parser.parse_token(PDF::Reader::PagesStrategy::OPERATORS))
    if token.kind_of?(PDF::Reader::Token) && PDF::Reader::PagesStrategy::OPERATORS.has_key?(token)
      operator = PDF::Reader::PagesStrategy::OPERATORS[token]
      if operator == :concatenate_matrix && params.length == 6
        # Set the matrix once, for all pages.
        pdf.transformation_matrix(*params)
      end
      # If first token was not a concatenate_matrix operator, then do nothing.
      return
    else
      params << token
    end
  end
end

Prawn::Document.generate(
  pdf_tempfile,
  template: template_pdf.path,
) do |pdf|

  # Set the transformation matrix for Google Chrome / Google Docs
  set_transformation_matrix(pdf, template_pdf.path)

  # Rest of your PDF code
  # ...

end
```

Note that this code works great for documents from Google Docs or Chrome, and it should just ignore PDFs from anywhere else. But I haven't tested with a large number of PDFs from various sources, and it will break if PDFs are starting each page with a different transformation. In practice, I think that would be very rare.

**Comment by pointlessone** [comment]
Just to be clear, this check will catch any page that starts with setting a transformation matrix (even when it doesn't last the whole page, or is identical to default matrix, or other matrix that doesn't flip the page). This is not specific to Chrome. It's a viable workaround when you know your template comes from Chrome but is not quite sufficient in case the source of template (and intent of the initial transformation) is unknown.

**Comment by ndbroadbent** [comment]
That's a good point. I'm really not sure of the best way to do this, but it would make sense to be very specific with the check. I'll check if the matrix starts with `1, 0, 0, -1`. It's just a heuristic and might have some false positives, but hopefully not.

**Comment by gettalong** [comment]
@ndbroadbent The problem with the `cm` operator in PDF content streams is that it is potentially not inversible because some matrices don't have inverse matrices. 

However, I think the best solution is to just encapsulate everything of the template between `q` and `Q` operators so that there is a pristine graphics state when Prawn starts. This is can be accomplished without touching the template by adding an additional content stream containing just `q` before the content stream of the template page, and another one just afterwards containing `Q`.

**Comment by ndbroadbent** [comment]
@gettalong Yeah that sounds like a much better solution! I've just learned about the `q` and `Q` operators, and have also found the `#save_graphics_state` and `#restore_graphics_state` methods in Prawn.

I just tried calling `pdf.save_graphics_state` and `pdf.restore_graphics_state` at the beginning and end of my `Prawn::Document.generate` block, but that doesn't seem to work. The Prawn content is still inverted.

**Comment by ndbroadbent** [comment]
I'm trying to figure out the structure of this PDF generated by Google Docs using `qpdf --qdf`. I'm not sure if I'm reading the streams correctly, so please let me know if I've made any mistakes.

```
%% Page 1
%% Original object ID: 3 0
4 0 obj
<<
  /Contents [
    5 0 R
    7 0 R
  ]
  /MediaBox [
    0
    0
    612
    792
  ]
  /Parent 3 0 R
  /Resources <<
    /ExtGState <<
      /G0 9 0 R
      /Tr1 10 0 R
      /Tr2 11 0 R
      /Tr3 12 0 R
    >>
```

So as far as I can tell, the object ids 9, 10, and 11 are the original PDF, and Prawn adds the `/Tr3 12`. 

ID 10 just contains this:

```
%% Original object ID: 10 0
10 0 obj
<<
  /CA 1
  /Type /ExtGState
  /ca 1
>>
endobj
```

ID 11 starts like this:

```
%% Contents for page 1
%% Original object ID: 11 0
5 0 obj
<<
  /Length 6 0 R
>>
stream
1 0 0 -1 0 792 cm
q
...
```

So the `cm` operator is right when the stream starts, followed by a call to `q`.

ID 12 starts like this:

```

%% Contents for page 1
%% Original object ID: 12 0
7 0 obj
<<
  /Length 8 0 R
>>
stream
q

...

Q
endstream
endobj
```

So it looks like the Prawn stream is properly wrapped inside `q` and `Q`, but it's not resetting the transformation, because that's happening outside a `q`/`Q` block?

I can actually fix the problem by wrapping the original stream from object 11 inside an additional `q` and `Q`, like this:

```
%% Contents for page 1
%% Original object ID: 11 0
5 0 obj
<<
  /Length 6 0 R
>>
stream
q
1 0 0 -1 0 792 cm
q

...

Q
Q
endstream
endobj
```

But that's the stream from the original template.

**Comment by ndbroadbent** [comment]
Here's an example PDF demonstrating the problem: 
[vertical-flip-example.pdf](https://github.com/prawnpdf/prawn-templates/files/1352854/vertical-flip-example.pdf)

**Comment by gettalong** [comment]
You are on track but re-read what I have written: You don't need to edit the content stream, you just have to add two new content streams, one with just `q` and one with just `Q`.

In PDF a page object has an entry called `Contents`. This entry can hold either a single reference to a content stream, or an array of references to content streams. This latter feature is what's needed to make this work. I.e. the value of `Contents` has to look something like this `[1 0 R 2 0 R 3 0 R 4 0 R]` where the PDF references are to objects like these:

~~~
1 0 obj
<</Length 1>>
stream
q
endstream
endobj

2 0 obj
... this is the content stream from the page template
endobj

3 0 obj
<</Length 1>>
stream
Q
endstream
endobj

4 0 obj
... this is the content stream from Prawn
endobj
~~~

**Comment by ndbroadbent** [comment]
Ohhh, sorry now I get it! That makes total sense. I've opened a tentative PR here where I'm working on that approach - https://github.com/prawnpdf/prawn-templates/pull/20

Not sure how to write tests for this, though. Ideally I would want to test that the Prawn content is not flipped upside down, but that's more of a presentational thing, and hard to test in code.
