### ISSUE TITLE
page layout ignored when generating pdf from template pdf 

### ISSUE THREAD

**Issue by AndrewSwerlick** [prawnpdf/prawn-templates#7]
This is a https://github.com/prawnpdf/prawn/issues/293. I ran into this issue and figured out the cause and a workaround that I'm using via monkey patching. I'm posting my analysis of the bug here since apparently there's an attempt to revive the templates code.

The problem lives in PDF::Core::Page. Basically when templates are used, the size instance variable does not get set, so calls to page.size just return the dimensions. However, when this value is fed back into Page.new to create a new page, it reverses the coordinates if the layout is landscape. Since page.size already gives you the coordinates in landscape, reversing them makes it portrait. The below change to the method ensures that the size method always returns coordinates as if the layout was portrait

```
module PDF
  module Core
    class Page
      def size
        return @size if defined?(@size) && @size

        case(layout)
        when :portrait
           dimensions[2,2]
        when :landscape
           dimensions[2,2].reverse
        end
      end
    end
  end
end
```

This would be tricky to fix for real since it's in pdf core, but it might represent a legitimate bug there too.

**Comment by bvogel** [comment]
Is this still "a thing" and if so wouldn't it be the correct way to set `size` based on the inserted template?

**Comment by bvogel** [comment]
as no one seems to care, I'm closing this.
